qlib_init:
    provider_uri: "~/.qlib/qlib_data/my_data"
    region: cn
market: &market csi300
benchmark: &benchmark SH000300
data_start_time: &data_start_time 2008-01-01
end_fit_time: &end_fit_time 2018-12-31
valid_start_time: &valid_start 2019-01-01
valid_end_time: &valid_end 2019-12-31
test_start: &test_start 2020-01-01
data_end_time: &data_end_time 2024-03-18
data_handler_config: &data_handler_config
    start_time: *data_start_time
    end_time: *data_end_time
    fit_start_time: *data_start_time
    fit_end_time: *end_fit_time
    instruments: *market
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: *test_start
        end_time: *data_end_time
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: ADD
        module_path: qlib.contrib.model.pytorch_add
        kwargs:
            d_feat: 6
            hidden_size: 64
            num_layers: 2
            dropout: 0.1
            dec_dropout: 0.0
            n_epochs: 200
            lr: 1e-3
            early_stop: 20
            batch_size: 5000
            metric: ic
            base_model: GRU
            gamma: 0.1
            gamma_clip: 0.2
            optimizer: adam
            mu: 0.2
            GPU: 0
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [*data_start_time, *end_fit_time]
                valid: [*valid_start, *valid_end]
                test: [*test_start, *data_end_time]
    record:
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            config: *port_analysis_config
